using System.IO;

namespace Launcher.App.Services;

public sealed class BootstrapService
{
    public string AppRoot { get; }
    public string DataRoot => Path.Combine(AppRoot, "data");
    public string LogsRoot => Path.Combine(DataRoot, "logs");
    public string CacheRoot => Path.Combine(DataRoot, "cache");
    public string ProfilesPath => Path.Combine(DataRoot, "profiles.json");
    public string SettingsPath => Path.Combine(DataRoot, "settings.json");
    public string ManifestSnapshotPath => Path.Combine(DataRoot, "manifest.snapshot.json");

    public BootstrapService(string appRoot)
    {
        AppRoot = appRoot;
    }

    public async Task EnsureDefaultsAsync(CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(DataRoot);
        Directory.CreateDirectory(LogsRoot);
        Directory.CreateDirectory(CacheRoot);

        var baseDir = AppContext.BaseDirectory;
        var profilesAssetPath = Path.Combine(baseDir, "Assets", "profiles.json");
        var settingsAssetPath = Path.Combine(baseDir, "Assets", "settings.json");
        var manifestAssetPath = Path.Combine(baseDir, "Assets", "manifest.json");

        await CopyIfMissingAsync(profilesAssetPath, ProfilesPath, cancellationToken);
        await CopyIfMissingAsync(settingsAssetPath, SettingsPath, cancellationToken);
        await CopyIfMissingAsync(manifestAssetPath, ManifestSnapshotPath, cancellationToken);

        // Migrate old placeholder / legacy snapshots generated by early builds.
        await ReplaceIfPlaceholderAsync(profilesAssetPath, ProfilesPath, cancellationToken);
        await ReplaceIfPlaceholderAsync(manifestAssetPath, ManifestSnapshotPath, cancellationToken);
    }

    private static async Task CopyIfMissingAsync(string source, string target, CancellationToken cancellationToken)
    {
        if (File.Exists(target))
        {
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(target) ?? ".");
        await using var sourceStream = File.OpenRead(source);
        await using var targetStream = File.Create(target);
        await sourceStream.CopyToAsync(targetStream, cancellationToken);
    }

    private static async Task ReplaceIfPlaceholderAsync(string source, string target, CancellationToken cancellationToken)
    {
        if (!File.Exists(source) || !File.Exists(target))
        {
            return;
        }

        var sourceJson = await File.ReadAllTextAsync(source, cancellationToken);
        if (ContainsPlaceholder(sourceJson))
        {
            return;
        }

        var targetJson = await File.ReadAllTextAsync(target, cancellationToken);
        if (!ContainsPlaceholder(targetJson) && !ContainsLegacyLizzieZip(targetJson))
        {
            return;
        }

        await File.WriteAllTextAsync(target, sourceJson, cancellationToken);
    }

    private static bool ContainsPlaceholder(string content)
    {
        return content.Contains("REPLACE", StringComparison.OrdinalIgnoreCase) ||
               content.Contains("example.com", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ContainsLegacyLizzieZip(string content)
    {
        return content.Contains("/lizzieyzy/releases/download/", StringComparison.OrdinalIgnoreCase) &&
               content.Contains("LizzieYzy.zip", StringComparison.OrdinalIgnoreCase);
    }
}
